runs_dir: output/kaijie_chen_7_a_rock_cliff_with_a_cave_in_the_wall_--ar_11_--_bdb61c7e-257d-4f68-9e2b-6a44699a3f26_1
example_name: kaijie_chen_7_a_rock_cliff_with_a_cave_in_the_wall_--ar_11_--_bdb61c7e-257d-4f68-9e2b-6a44699a3f26_1

seed: 1
# enable guided depth diffusion
depth_conditioning: True

# use gpt to generate scene description
use_gpt: False
debug: True

# depth model and camera/depth parameters
depth_model: depth_anything
camera_speed: 0.001
fg_depth_range: 0.015
depth_shift: 0.001
sky_hard_depth: 0.02
init_focal_length: 960

# re-generate sky panorama images
gen_sky_image: False
# generate sky point cloud
gen_sky: False

# enable layer-wise generation
gen_layer: True
# load previously generated gaussians
load_gen: False